apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://spring-petclinic-angular:4200;
      }

      location /petclinic/api {
        proxy_pass http://spring-petclinic-rest:9966/petclinic/api/;
      }
    }