---
    version: '3.7'
    services:
      nginx:
        image: team1qa/nginx:laetst
          context: .
          dockerfile: Dockerfiles/nginx/Dockerfile
        ports:
          - target: 80
            published: 80
            protocol: tcp

      backend:
        image: team1qa/backend:latest
        build:
          context: .
          dockerfile: Dockerfiles/PetClinicREST/Dockerfile
        ports:
          - target: 9966
            published: 9966
            protocol: tcp

      frontend:
        image: team1qa/frontend:latest
        build:
          context: .
          dockerfile: Dockerfiles/PetClinicAngular/Dockerfile
        ports:
        - target: 4200
          published: 4200
          protocol: tcp
        depends_on:
        - backend
...
