---
    version: '3.7'
    services:
      backend:
        image: team1qa/backend:latest
        build:
          context: .
          dockerfile: spring-petclinic-rest/Dockerfile
        ports:
          - target: 9966
            published: 9966
            protocol: tcp
      frontend:
        image: team1qa/frontend:latest
        build:
          context: .
          dockerfile: spring-petclinic-angular/Dockerfile
        ports:
        - target: 4200
          published: 4200
          protocol: tcp
        depends_on:
        - backend
...
