---
    version: '3.7'
    services:
      backend:
        image: team1qa/backend:latest
        build:
          context: .
          dockerfile: Dockerfiles/PetClinicREST/Dockerfile
        ports:
          - target: 9966
            published: 9966
            protocol: tcp
...
