apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend

spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2

  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: backend
        image: team1qa/frontend
        ports:
        - containerPort: 4200

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 4200
    targetPort: 4200
    protocol: TCP
